<a href="https://colab.research.google.com/github/asadpro/Tensorflow-Day-to-Day-Practice/blob/main/Day_2_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# Tensor multiplication with @ symbol
tensor_1 = tf.constant([[3,4],[7,9]])
tensor_2 = tf.constant([[3,2],[6,8]])

tensor_1 @ tensor_2

## Taking transpose of mismatch matrix and then do multiplication or we can also reshape the tensors to solve the same problem.

**[Matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html)**
- *#Matrix multiplication with Python operator '@'*


In [ ]:
# First try transposing the tensor
# Create (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
x = tf.transpose(x) # We take tranpose of one matrix to make the inner dimension equal:
x @ y

In [ ]:
# Now solve the above problem by reshaping the matrix
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

x = tf.reshape(x,shape=(2,3)) 
x@y

In [ ]:
# We can achieve the same result as above with parameters
t1 = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

t2 = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

tf.matmul(t1,t2,transpose_a=True, transpose_b=False)

In [ ]:
# Tensor multiplication using tensordot method
t3 = tf.constant([
                  [2,3],
                  [3,3]
                  
                  ])
t4 = tf.constant([
                  [4,5],
                  [5,5]
                  
                  ])
tf.tensordot(t3,t4,axes=1)



# **Markdown commands to use**
<code> Code snippet </code><br>
- Hello
- World 
* Hi Flutter
  * Welcome pro
  * I am linux
    * The OS

  >This is a blockquote
# Heading 1
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6
```
Print('Hello tensorflow')
Print('Hello tensorflow')
Print('Hello tensorflow')
```

- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media<br>

~~The world is flat.~~ We now know that the world is round.
Gone camping! :tent: Be back soon.<br>
## We can add emoji directly from copying like from emojipedia 😗 

I need to highlight these <mark>very important words</mark>.

H<sub>2</sub>O <br>
H<sup>2</sup>O <br>
[Click on site](http://www.google.com)


In [ ]:
# Create a new tensor with default datatype (float32)
b = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
c = tf.constant([1, 7])
b,c


In [ ]:
from numpy import float16
b = tf.dtypes.cast(b,dtype=float16)
b.dtype

##**SparseTensor vs Tensor**
- When a tensor contain many zeros like below tensor then it's called sparseTensor.
- Tensor are the simple tensor which contain some numerical values.
### **Why we need SparseTensor**
- SparseTensor is needed when we have an image which contain lots of dark pixel which is detoned by zero so we simply mitigate those dark pixel denoted by zero and take the actual values and their corresponding indices and shape which reduce computation time of our GPU instead of calculating the zeros values also.
![SparseTensor](https://i.stack.imgur.com/8J9Uo.jpg)<br>
[Explore SparseTensor Further](https://stackoverflow.com/questions/47662143/what-is-the-difference-between-tensors-and-sparse-tensors)


In [ ]:
# [0, 7, 0, 0, 8, 0, 0, 0, 0]
x = tf.SparseTensor(values=[7,8],indices=[[1],[4]],dense_shape=[9])
print(x)

In [ ]:
# Finding sum, min, max, mean of a tensor
tensor = tf.constant(np.random.randint(low=0,high=100,size=50))
prod = tf.constant([[2,3],[2,8]])

print(f'Minimum of tensor: ',tf.reduce_min(tensor).numpy())
print(f'Maximum of tensor: ',tf.reduce_max(tensor).numpy())
print(f'Sum of tensor: ',tf.reduce_sum(tensor).numpy())
print(f'Mean of tensor: ',tf.reduce_mean(tensor).numpy())
print(f'Product of tensor: ',tf.reduce_prod(prod).numpy())

# Find the maximum element position of tensor element

print(f'Index of maximum value in a tensor: ',tf.argmax(tensor).numpy())
print(f'Index of minimum value in a tensor: ',tf.argmin(tensor).numpy())


## Squeezing the tensor and removing all single dimensions from a tensor.

In [ ]:
# Reshaping the tensor 5D to 1D by using squeeze method
squeeze = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
squeezed = tf.squeeze(squeeze)
squeezed.ndim

In [ ]:
# Reshaping the tensor from 5D to 1D by using reshaped method -1

reshape = tf.reshape(squeeze,shape=(-1))
reshape.ndim

## **One-hot encoding** is needed when you want to convert categorical data in 0 and 1 format. Categorical input feature are convert into numerical encoding before feed it to the neural network.

In [ ]:
# One hot encoding is need. Let's take an example catergorical data
rollNo = [1,3,2,4]
tf.one_hot(rollNo,depth=len(rollNo))



In [ ]:
# tf.fill() method will fill the tensor with scalar value

scalar = tf.fill([3,3],4)
scalar


In [ ]:

square_tensor = tf.constant([1.2,4.2,6.2])

print('Square of tensor: ',tf.square(square_tensor).numpy())
print('Log of tensor: ',tf.math.log(100.0).numpy())
print('SquareRoot of tensor: ',tf.sqrt(square_tensor).numpy())


## **Manipulating `tf.Variable` tensors**
### We have discuss two method **`assign`** and **`assign_add`** both of these methods have their own use look at the below practical implementation:
> ### 💡 we can convert tensor into numpy array as well like => tensor.numpy()

In [ ]:
# assign method add a new value to the existing value in a tensor
changeable = tf.Variable([1,2,3,4])

changeable[0].assign(11)

# assign_add method add 10 with every element inside of tensor but shape of both tensors must be the same.
new = tf.constant([10,10,10,10]) 
changeable.assign_add(new)
new.numpy()


In [ ]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
t1 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))
t2 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))

# Multiply the two tensors you created in 3 using matrix multiplication.

tensor_mul = tf.tensordot(t1,t2,axes=0)
resul1 = tf.matmul(tf.transpose(t1),t2)


In [ ]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
t3 = tf.random.uniform(minval=0,maxval=1,shape=(224, 224, 3))
min = tf.argmin(t3)
max = tf.argmax(t3)

print('Minimum value : ',min)
print('Maximum value : ',max)


In [ ]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(1, 224, 224, 3))
random_tensor

# Squeezing the above tensor to remove single-dimension from it.

tf.squeeze(random_tensor).shape

TensorShape([224, 224, 3])

In [ ]:
from numpy import int16
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
last_tensor = tf.constant([5,3,2,1,6,7,8,9,10,2])
tf.argmax(last_tensor)


# One-hot encode the tensor you created in 9.
tf.one_hot(last_tensor,depth=10,dtype=int16)


<tf.Tensor: shape=(10, 10), dtype=int16, numpy=
array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)>

In [ ]:
values = [1, 10, 26.9, 2.8, 166.32, 62.3]
sorted = tf.argsort(values,direction='DESCENDING',)
sorted

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 5, 2, 1, 3, 0], dtype=int32)>

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
# Creating a model for minist dataset
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128,activation='relu',))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(10))

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions


array([[-0.46107742, -0.35958225,  0.12863302,  0.39512253,  0.26128218,
         0.29148144,  0.45146337, -0.21050139,  0.0617248 , -0.10353111]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.05767621, 0.06383745, 0.10401709, 0.1357812 , 0.11877184,
        0.12241337, 0.14365083, 0.07410039, 0.09728522, 0.08246642]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn
loss_fn(y_train[:1], predictions).numpy()

2.1003516

In [ ]:
model.compile(optimizer='Adam',loss=loss_fn,metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1354 - accuracy: 0.9607
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1007 - accuracy: 0.9690
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0852 - accuracy: 0.9736
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0718 - accuracy: 0.9777
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0628 - accuracy: 0.9803


In [ ]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0756 - accuracy: 0.9785 - 581ms/epoch - 2ms/step


[0.07563818246126175, 0.9785000085830688]